Repository Bhanu-code/db-drawer, pull requests merged in 2024-05, with the labels that each got.

#50 feat: automate greetings using github bot
  .github/workflows/greetings.yml
Labels: gssoc, level1

#45 fixesIssue#44
  public/styles/sqlz.css
  views/sqlz.ejs
Labels: gssoc, level1

#52 chore: Update shebang line in index.js
  index.js
Labels: bug, level2, gssoc

#55 created css variables for colors properties in ejs
  public/styles/prisma.css
  public/styles/style.css
  views/mongo.ejs
  views/prisma.ejs
  views/sqlz.ejs
Labels: gssoc, level1

#57 chore: Remove console.log statement in mongo.ejs
  views/mongo.ejs
Labels: gssoc, level1

#69 added workflow as per issue #66
  .github/workflows/autocomment-iss-close.yml
Labels: level2, gssoc

#68 added workflow as per issue #63
  .github/workflows/autocomment-pr-merge.yml
Labels: level2, gssoc
